format = '''
[$username@$hostname](gray) [$directory](white)[$git_status](gray) [$character](symbol)$jobs'''
right_format = ''

palette = 'fish'

[palettes.fish]
symbol = '#d91432'
vim = '#717375'
gray = '#A0A0A0'

[username]
show_always = true
format = '$user'

[hostname]
ssh_only = false
format = '$hostname'

[git_status]
format = '$all_status'

[character]
success_symbol = '[\$](symbol)'
error_symbol = '[\$](symbol)'
vimcmd_symbol = '[\$](vim)'

[directory]
style = 'bold white'
truncation_length = 1
format = '[$path]($style)[$read_only]($read_only_style)'
